// examples/frameworks/svelte-basic/src/App.svelte
<script>
  let label = "Ready";
  let items = [{ id: "feature-native" }, { id: "feature-fast" }];

  function handlePress() {
    label = "Pressed";
  }

  function handleMount() {
    label = "Mounted";
  }

  function handleDestroy() {
    label = "Unmounted";
  }
</script>

<hawk-view id="root" use:root_ref class="surface.card" data-asset="assets/logo.svg" on:mount={handleMount} on:destroy={handleDestroy}>
  <hawk-text id="title">Svelte Hawk2UI</hawk-text>
  <hawk-button id="cta" on:press={handlePress}>{label}</hawk-button>
  {#each items as item (item.id)}
    <hawk-text id={item.id}>{item.id}</hawk-text>
  {/each}
</hawk-view>

// examples/frameworks/vue-basic/src/App.vue
<script setup>
import { ref } from "vue";

const label = ref("Ready");
const items = [{ id: "feature-native" }, { id: "feature-fast" }];

function handlePress() {
  label.value = "Pressed";
}

function handleMount() {
  label.value = "Mounted";
}

function handleUnmount() {
  label.value = "Unmounted";
}
</script>

<template>
  <hawk-view id="root" ref="root_ref" class="surface.card" data-asset="assets/logo.svg" @mounted="handleMount" @unmounted="handleUnmount">
    <hawk-text id="title">Vue Hawk2UI</hawk-text>
    <hawk-button id="cta" @pointerdown="handlePress">{{ label }}</hawk-button>
    <hawk-text v-for="item in items" :id="item.id" :key="item.id">{{ item.id }}</hawk-text>
  </hawk-view>
</template>
