// examples/frameworks/react-basic/src/App.tsx
import { useState } from "react";

export function App() {
  const [label, setLabel] = useState("Ready");
  const items = [{ id: "feature-native" }, { id: "feature-fast" }];

  function handlePress() {
    setLabel("Pressed");
  }

  function handleMount() {
    setLabel("Mounted");
  }

  function handleUnmount() {
    setLabel("Unmounted");
  }

  return (
    <hawk-view
      id="root"
      ref="root_ref"
      className="surface.card"
      data-asset="assets/logo.svg"
      onMount={handleMount}
      onUnmount={handleUnmount}
    >
      <hawk-text id="title">React Hawk2UI</hawk-text>
      <hawk-button id="cta" onPointerDown={handlePress}>{label}</hawk-button>
      {items.map((item) => <hawk-text id={item.id} key={item.id}>{item.id}</hawk-text>)}
    </hawk-view>
  );
}

// examples/frameworks/vue-basic/src/App.vue
<script setup>
import { ref } from "vue";

const label = ref("Ready");
const items = [{ id: "feature-native" }, { id: "feature-fast" }];

function handlePress() {
  label.value = "Pressed";
}

function handleMount() {
  label.value = "Mounted";
}

function handleUnmount() {
  label.value = "Unmounted";
}
</script>

<template>
  <hawk-view id="root" ref="root_ref" class="surface.card" data-asset="assets/logo.svg" @mounted="handleMount" @unmounted="handleUnmount">
    <hawk-text id="title">Vue Hawk2UI</hawk-text>
    <hawk-button id="cta" @pointerdown="handlePress">{{ label }}</hawk-button>
    <hawk-text v-for="item in items" :id="item.id" :key="item.id">{{ item.id }}</hawk-text>
  </hawk-view>
</template>
