// examples/vue-plugin-basic/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import {
  beginAutomationGesture,
  endAutomationGesture,
  getTransport,
  loadPreset,
  loadState,
  readParameter,
  savePreset,
  saveState,
  writeParameter,
} from "hawk:plugin";
import { subscribeMeters } from "hawk:audio";
import { sendControl } from "hawk:dsp";

const gain = ref(0);
const meter = ref("meter:pending");
const transport = ref("transport:pending");
const state = ref("state:pending");
const preset = ref("preset:pending");

onMounted(async () => {
  gain.value = await readParameter("gain");
  const meterFrame = await subscribeMeters({ source: "master" });
  meter.value = `meter:${meterFrame.source}=${meterFrame.values.join(",")}`;
  const snapshot = await getTransport();
  transport.value = `transport:${snapshot.playing}:${snapshot.sampleRate}`;
  const beforeState = await loadState();
  await saveState(JSON.stringify({ preset: "Wide", version: 2 }));
  state.value = `state:${beforeState}->${await loadState()}`;
  const beforePreset = await loadPreset("init");
  await savePreset("init", JSON.stringify({ name: "Wide", version: 2 }));
  preset.value = `preset:${beforePreset}->${await loadPreset("init")}`;
  await sendControl({ type: "ui-ready", source: "vue-plugin-basic" });
});

async function boost() {
  await beginAutomationGesture("gain");
  await writeParameter("gain", 0.75);
  await endAutomationGesture("gain");
  gain.value = await readParameter("gain");
  await sendControl({ type: "automation", parameter: "gain", value: gain.value });
}
</script>

<template>
  <hawk-view id="vue-plugin-root" role="group" aria-label="Vue plugin editor">
    <hawk-text id="gain" role="status" label="Gain">{{ gain.toFixed(2) }}</hawk-text>
    <hawk-text id="meter">{{ meter }}</hawk-text>
    <hawk-text id="transport">{{ transport }}</hawk-text>
    <hawk-text id="state">{{ state }}</hawk-text>
    <hawk-text id="preset">{{ preset }}</hawk-text>
    <hawk-button id="boost" @pointer-press="boost">Boost</hawk-button>
  </hawk-view>
</template>

// examples/react-plugin-basic/src/App.tsx
import React, { useEffect, useState } from "react";
import { createRoot } from "@hawk2ui/react";
import {
  beginAutomationGesture,
  endAutomationGesture,
  getTransport,
  loadPreset,
  loadState,
  readParameter,
  savePreset,
  saveState,
  writeParameter,
} from "hawk:plugin";
import { subscribeMeters } from "hawk:audio";
import { sendControl } from "hawk:dsp";

function App() {
  const [gain, setGain] = useState(0);
  const [meter, setMeter] = useState("meter:pending");
  const [transport, setTransport] = useState("transport:pending");

  useEffect(() => {
    setGain(readParameter("gain"));
    setMeter(JSON.stringify(subscribeMeters({ ids: ["main"], intervalMs: 16 })));
    setTransport(JSON.stringify(getTransport()));
    if (loadState() === "") {
      saveState("gain=0.25");
    }
    loadPreset("factory.default");
    savePreset("factory.snapshot", "gain=0.25");
    sendControl({ type: "ui-ready", source: "react-plugin-basic" });
  }, []);

  function boost() {
    beginAutomationGesture("gain");
    writeParameter("gain", 0.75);
    endAutomationGesture("gain");
    const nextGain = readParameter("gain");
    setGain(nextGain);
    sendControl({ type: "automation", parameter: "gain", value: nextGain });
  }

  return (
    <view id="react-plugin-root" role="group" ariaLabel="React plugin editor">
      <text id="gain" role="status" label="Gain">
        {gain.toFixed(2)}
      </text>
      <text id="meter">{meter}</text>
      <text id="transport">{transport}</text>
      <button id="boost" onPointerPress={boost}>
        Boost
      </button>
    </view>
  );
}

createRoot("editor").render(<App />);
